version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: bens-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  chess:
    build:
      context: .
      args:
        BINARY_PATH: .stack-work/install/x86_64-linux-tinfo6/3e8262f63fe32efb8f698f489b0cca67f52ac710d0084caa03b0f552ad65a94a/8.10.7/bin/chess-exe
    image: ben/chess
    command: /chess/chess-app/chess-exe
    ports:
      - "3000:3000"
