version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: bens-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  chess:
    build:
      context: .
    image: ben/chess
    command: /chess/chess-app/chess-exe
    ports:
      - "3000:3000"
