version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: bens-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  opening-table:
    build: 
      context: .
      dockerfile: ./app/Chess/OpeningTable/Dockerfile
    image: ben/opening-table
    container_name: opening-table
    command: /chess/chess-app/opening-table-exe
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
  # chess:
  #   build:
  #     context: .
  #     dockerfile: ./app/Chess/Dockerfile
  #   image: ben/chess
  #   container_name: chess
  #   command: /chess/chess-app/chess-exe
  #   ports:
  #     - "3001:3001"
  #   depends_on: [postgres, opening-table]
