version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: bens-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  chess:
    build:
      context: .
      args:
        BINARY_PATH: .stack-work/install/x86_64-linux-tinfo6/99b239cf070f65f8fd7a3f80e8b11fa42584c86a5de5391cf1129f46c20794f3/9.2.7/bin/chess-exe
    image: ben/chess
    command: /chess/chess-app/chess-exe
    ports:
      - "3000:3000"
    depends_on: [postgres]
