version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: bens-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  opening-table:
    build: 
      context: .
      dockerfile: ./app/Chess/OpeningTable/Dockerfile
    image: ben/opening-table
    container_name: opening-table
    command: /chess/chess-app/opening-table-exe
    ports:
      - "3000:3000"
    depends_on: [postgres]
  # chess:
  #   build:
  #     context: .
  #     dockerfile: ./app/Chess/Dockerfile
  #   image: ben/chess
  #   container_name: chess
  #   command: /chess/chess-app/chess-exe
  #   ports:
  #     - "3001:3001"
  #   depends_on: [postgres, opening-table]
