name:                chess
version:             0.1.0.0
github:              "githubuser/chess"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chess#readme>

dependencies:
- adjunctions
- aeson
- array
- barbies
- base >= 4.7 && < 5
- bytestring
- containers
- distributive
- esqueleto
- hspec
- http-client
- http-types
- lens
- monad-logger
- mtl
- persistent
- persistent-postgresql
- QuickCheck
- raw-strings-qq
- regex-tdfa
- servant
- servant-client
- servant-server
- split
- text
- transformers
- unliftio
- validation
- wai
- warp
- yaml

library:
  source-dirs: src

executables:
  opening-table-exe:
    main:                Chess/OpeningTable/OpeningTableApp.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Chess.OpeningTable.OpeningTableApp
    dependencies:
    - chess
  # chess-exe:
  #   main:                Chess/ChessApp.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   - -main-is Chess.ChessApp
  #   dependencies:
  #   - chess

tests:
  chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess
